id: 'MyMalware'
inputs: []
name: MyMalware
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ecc7cfc9-5e79-48ac-86a6-832c7508dd72
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: ecc7cfc9-5e79-48ac-86a6-832c7508dd72
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: This is my first task
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 54f867c4-8a46-475f-8163-8f4846f4ddd0
      iscommand: false
      name: Check File
      script: Print
      type: regular
      version: -1
    taskid: 54f867c4-8a46-475f-8163-8f4846f4ddd0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7008cbd9-004c-42be-8a17-5c4a9b0811a5
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 7008cbd9-004c-42be-8a17-5c4a9b0811a5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 365,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: This is my Malware Playbook
