id: 'AcmeaPhishing'
inputs: []
name: AcmeaPhishing
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 10eef4bf-7d9b-4948-8dd1-fd70b9bcbe93
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 10eef4bf-7d9b-4948-8dd1-fd70b9bcbe93
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: This worked well
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 41344094-d133-4b41-8b50-f55570ef875a
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: 41344094-d133-4b41-8b50-f55570ef875a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5a3ec5cf-d8f6-494f-81d8-edc7aef49b71
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 5a3ec5cf-d8f6-494f-81d8-edc7aef49b71
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 380
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 395,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: This playbook is designed for phishing incidents
