id: 'MyPhishing'
inputs: []
name: MyPhishing
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 62ffd9d7-626c-46c3-805c-910a3f66c674
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 62ffd9d7-626c-46c3-805c-910a3f66c674
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 670,
          "y": -60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: This is my first task
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 38a10112-e519-4e23-89b0-bf34c3637116
      iscommand: false
      name: Phishing
      script: Print
      type: regular
      version: -1
    taskid: 38a10112-e519-4e23-89b0-bf34c3637116
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 670,
          "y": 130
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ed7121fd-b424-453d-86d7-4cda9cccec3f
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: ed7121fd-b424-453d-86d7-4cda9cccec3f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 660,
          "y": 330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 390,
        "x": 660,
        "y": -60
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: This is a phishing Playbook
