id: 'DemoPB'
inputs: []
name: DemoPB
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32e0e127-2f09-46ae-894e-87e9ebe0af72
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 32e0e127-2f09-46ae-894e-87e9ebe0af72
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      description: "task description"
      brand: ""
      id: 7ecff0cf-1ddd-497e-8b07-20a39b29d128
      iscommand: false
      name: DemoPrint
      script: 'DemoPrint'
      type: regular
      version: -1
    taskid: 7ecff0cf-1ddd-497e-8b07-20a39b29d128
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 215,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.10.0
description: demo playbook.
