contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: 71dd569a-d45e-42ce-8b10-2cb2717192ff
    packName: PushwithPR
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 2a7d2dd6-694e-4649-89e8-20fbb841175f
inputs: []
name: PlaybookPUSHWithPR
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3eb54cb1-3bbd-4df1-858b-7872bf6489f8
      iscommand: false
      name: ""
      version: -1
    taskid: 3eb54cb1-3bbd-4df1-858b-7872bf6489f8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: This is something
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: d5989ef3-c49f-4e4a-8d7d-e2061ea39972
      iscommand: false
      name: Print Something
      scriptName: Print
      type: regular
      version: -1
    taskid: d5989ef3-c49f-4e4a-8d7d-e2061ea39972
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 71fdb24f-f1ad-4a10-8537-34e686a3fb80
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 71fdb24f-f1ad-4a10-8537-34e686a3fb80
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 345,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
